version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: web_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask_app
    networks:
      - webnet

  flask_app:
    build:
      context: .
    container_name: flask_app
    volumes:
      - ./app:/app
    networks:
      - webnet

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2301921@sit.singaporetech.edu.sg
      MYSQL_USER: admin
      MYSQL_PASSWORD: 2301921@sit.singaporetech.edu.sg
      MYSQL_DATABASE: myapp
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 2301921@sit.singaporetech.edu.sg
    depends_on:
      - db
    networks:
      - webnet

  gitea:
    image: gitea/gitea:1.22
    container_name: gitea
    restart: always
    ports:
      - "3001:3000"   # Web UI
      - "2223:22"     # SSH access
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__server__DOMAIN: 127.0.0.1
      GITEA__server__ROOT_URL: http://127.0.0.1:3001/
      GITEA__server__SSH_PORT: 2223
      GITEA__service__DISABLE_REGISTRATION: "true"
    volumes:
      - ./gitea/data:/data
    networks:
      - webnet

networks:
  webnet:

volumes:
  db_data:
